---
broker: 'redis://127.0.0.1:6379'
default_queue: machinery_tasks
result_backend: 'redis://127.0.0.1:6379'
results_expire_in: 3600000
amqp:
  binding_key: machinery_tasks
  exchange: machinery_exchange
  exchange_type: direct
  prefetch_count: 3
